config/routes.rb
Rails.application.routes.draw do

  resources :comments
  resources :sites
  namespace :admin do
      resources :users, :delinquency_stats, :reports, :routes, :tips, :zones
      root to: "users#index"
    end
  resources :delinquency_stats, :reports, :routes, :tips, :zones

  devise_for :users, :path_prefix => 'sessions'
  resources :users do
    collection do
      put :update
    end
  end

  
  get "maps/fetch_comments/:id" => 'maps#refresh_comments', as: 'fetch_comments'
  get "pages/index"
  get "pages/services"
  get "pages/aboutus" 
  get "pages/tips"
  get "maps/map"  
  get "tipsservice/selection"  
  get "tipsservice/tip"  
  get "tipsservice/data"   
  root to: "pages#index"
end

app/models/zone.rb
class Zone < ApplicationRecord
  has_one :delinquency_stat
  has_and_belongs_to_many :tips
  has_and_belongs_to_many :routes
  has_and_belongs_to_many :reports
end

app/controllers/zones_controller.rb
class ZonesController < ApplicationController
  layout 'white'
  before_action :set_zone, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :authenticate_admin, :except => [:show]
  
  # GET /zones
  # GET /zones.json
  def index
    @zones = Zone.all
  end

  # GET /zones/1
  # GET /zones/1.json
  def show
  end

  # GET /zones/new
  def new
    @zone = Zone.new
  end

  # GET /zones/1/edit
  def edit
  end

  # POST /zones
  # POST /zones.json
  def create
    @zone = Zone.new(zone_params)

    respond_to do |format|
      if @zone.save
        format.html { redirect_to @zone, notice: 'Zone was successfully created.' }
        format.json { render :show, status: :created, location: @zone }
      else
        format.html { render :new }
        format.json { render json: @zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zones/1
  # PATCH/PUT /zones/1.json
  def update
    respond_to do |format|
      if @zone.update(zone_params)
        format.html { redirect_to @zone, notice: 'Zone was successfully updated.' }
        format.json { render :show, status: :ok, location: @zone }
      else
        format.html { render :edit }
        format.json { render json: @zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zones/1
  # DELETE /zones/1.json
  def destroy
    @zone.destroy
    respond_to do |format|
      format.html { redirect_to zones_url, notice: 'Zone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zone
      @zone = Zone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zone_params
      params.require(:zone).permit(:coordinate, :name, :CAI, :user_score, :influx)
    end
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/zones/_form.html.erb
<%= form_with(model: zone, local: true) do |form| %>
  <% if zone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(zone.errors.count, "error") %> prohibited this zone from being saved:</h2>

      <ul>
      <% zone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :coordinate %>
    <%= form.text_field :coordinate %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :CAI %>
    <%= form.number_field :CAI %>
  </div>

  <div class="field">
    <%= form.label :user_score %>
    <%= form.number_field :user_score %>
  </div>

  <div class="field">
    <%= form.label :influx %>
    <%= form.text_field :influx %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/zones/edit.html.erb
<h1>Editing Zone</h1>

<%= render 'form', zone: @zone %>

<%= link_to 'Show', @zone %> |
<%= link_to 'Back', zones_path %>

app/views/zones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Zones</h1>

<table>
  <thead>
    <tr>
      <th>Coordinate</th>
      <th>Name</th>
      <th>Cai</th>
      <th>User score</th>
      <th>Influx</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @zones.each do |zone| %>
      <tr>
        <td><%= zone.coordinate %></td>
        <td><%= zone.name %></td>
        <td><%= zone.CAI %></td>
        <td><%= zone.user_score %></td>
        <td><%= zone.influx %></td>
        <td><%= link_to 'Show', zone %></td>
        <td><%= link_to 'Edit', edit_zone_path(zone) %></td>
        <td><%= link_to 'Destroy', zone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Zone', new_zone_path %>

app/views/zones/new.html.erb
<h1>New Zone</h1>

<%= render 'form', zone: @zone %>

<%= link_to 'Back', zones_path %>

app/views/zones/show.html.erb
<p>
  <strong>Coordinate:</strong>
  <%= @zone.coordinate %>
</p>

<p>
  <strong>Name:</strong>
  <%= @zone.name %>
</p>

<p>
  <strong>Cai:</strong>
  <%= @zone.CAI %>
</p>

<p>
  <strong>User score:</strong>
  <%= @zone.user_score %>
</p>

<p>
  <strong>Influx:</strong>
  <%= @zone.influx %>
</p>

<%= link_to 'Edit', edit_zone_path(@zone) %> |
<%= link_to 'Back', zones_path %>